# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
    config.vm.define 'pxe_server' do |config|
      config.vm.box = "debian/jessie64" # "debian/stretch64"
      config.vm.box_version = "8.10.0" #"9.4.0"
      config.vm.synced_folder '.', '/vagrant', disabled: true
      config.vm.synced_folder '../assets/', '/var/lib/matchbox/assets', disabled: false
      config.ssh.insert_key = false

      config.vm.provision "shell", path: "scripts/matchbox_server.sh"
      config.vm.provision "shell", path: "scripts/etcd.sh"

      config.vm.provider :libvirt do |lv|
        lv.memory = "1024"
        lv.keymap = "de"
        lv.cpus = "1"
      end

      config.vm.provider :virtualbox do |vb|
        vb.memory = "1024"
        vb.cpus = "1"
        vb.name = "pxe_server"
      end

      # public network
      config.vm.network "private_network",
                        ip: "192.168.0.254",
                        libvirt__network_name: "pxe_network",
                        :libvirt__dhcp_enabled => false

      config.vm.network "private_network",
                        ip: "192.168.1.254",
                        libvirt__network_name: "pxe_network",
                        :libvirt__dhcp_enabled => false,
                        virtualbox__intnet: "pxe_network"
  end
end
